### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by defied** [jsknnr/zomboid-helm#3]
Did you ever get this working?
I'm trying to run it via argoCD and it looks like there is a race condition where the pod is waiting for pvc's to exist, however the pvc's are set to provision only when a pod is ready...

**Comment by defied** [comment]
I pulled out the pvc template, created my own.
cat /home/service-configs/volumes/zomboid_volume.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zomboid-pv-volume
  namespace: zomboid
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/zomboid/data"
 ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zomboid-pv-volume2
  namespace: zomboid
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/zomboid/config"
```
cat /home/service-configs/volumes/zomboid_pvc.yaml

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-zomboid-pvc-config
  namespace: zomboid
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-zomboid-pvc-data
  namespace: zomboid
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```

This works.
